
#define S3SS_VERSION_MAJOR 1
#define S3SS_VERSION_MINOR 6
#define S3SS_VERSION_PATCH 3

// Uncomment this as needed.
// #define S3SS_VERSION_LABEL "rc.1"

#define S3SS_VERSION_COMPONENT_STRINGIZE(component) #component
#define S3SS_VERSION_COMPONENT_STRING(component) S3SS_VERSION_COMPONENT_STRINGIZE(component)

#define S3SS_VERSION_MAJOR_STRING S3SS_VERSION_COMPONENT_STRING(S3SS_VERSION_MAJOR)
#define S3SS_VERSION_MINOR_STRING S3SS_VERSION_COMPONENT_STRING(S3SS_VERSION_MINOR)
#define S3SS_VERSION_PATCH_STRING S3SS_VERSION_COMPONENT_STRING(S3SS_VERSION_PATCH)

#ifdef S3SS_VERSION_LABEL
#define S3SS_VERSION_STRING S3SS_VERSION_MAJOR_STRING "." S3SS_VERSION_MINOR_STRING "." S3SS_VERSION_PATCH_STRING "-" S3SS_VERSION_LABEL
#else
#define S3SS_VERSION_STRING S3SS_VERSION_MAJOR_STRING "." S3SS_VERSION_MINOR_STRING "." S3SS_VERSION_PATCH_STRING
#endif
